# Generated by Django 4.2.16 on 2024-10-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=30)),
                ('club_stadium', models.CharField(max_length=30)),
                ('logo', models.CharField(max_length=30)),
                ('club_sponsor', models.CharField(max_length=40)),
                ('club_originality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_time', models.TimeField(auto_now=True)),
                ('fixture_date', models.DateField(auto_now=True)),
                ('fixtture_status', models.CharField(max_length=10)),
                ('referee', models.CharField(max_length=30)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.club')),
            ],
        ),
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=20)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('stutus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField()),
                ('yellow_card', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('possession', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.club')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.fixture')),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(auto_now=True)),
                ('position', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=4)),
                ('contact', models.CharField(max_length=40)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.club')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.season'),
        ),
    ]
